global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'panos_exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.1.15
          - 192.168.1.26
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9654  # or use your docker host/IP if running externally 